const inventory = [
  {
    id: -2,
    name: "rEmpty",
    attribute: "emp",
    group: "empty",
    source: "paparac",
    count: 9,
  },
  {
    id: -1,
    name: "aEmpty",
    attribute: "emp",
    group: "empty",
    source: "paparac",
    count: 99,
  },
  {
    id: 0,
    name: "empty",
    attribute: "emp",
    group: "empty",
    source: "paparac",
    count: 0,
  },
  {
    id: 1,
    name: "dirty",
    attribute: "oth",
    group: "other",
    source: "paparac",
    count: 8,
  },
  {
    id: 2,
    name: "dirtyClass",
    attribute: "cls",
    group: "class",
    source: "paparac",
    count: 9,
  },
  {
    id: 3,
    name: "fire",
    attribute: "oth",
    group: "other",
    source: "paparac",
    count: 3,
  },
  {
    id: 4,
    name: "fireClass",
    attribute: "cls",
    group: "class",
    source: "paparac",
    count: 42,
  },
  {
    id: 5,
    name: "water",
    attribute: "oth",
    group: "other",
    source: "paparac",
    count: 11,
  },
  {
    id: 6,
    name: "waterClass",
    attribute: "class",
    group: "other",
    source: "paparac",
    count: 5,
  },
  {
    id: 7,
    name: "energy",
    attribute: "oth",
    group: "other",
    source: "paparac",
    count: 5,
  },
  {
    id: 8,
    name: "energyClass",
    attribute: "cls",
    group: "class",
    source: "paparac",
    count: 1,
  },
  {
    id: 9,
    name: "earid",
    attribute: "met",
    group: "metal",
    source: "paparac",
    count: 6,
  },
  {
    id: 10,
    name: "firid",
    attribute: "met",
    group: "metal",
    source: "paparac",
    count: 5,
  },
  {
    id: 11,
    name: "watenid",
    attribute: "met",
    group: "metal",
    source: "paparac",
    count: 1,
  },
  {
    id: 12,
    name: "strumenid",
    attribute: "met",
    group: "metal",
    source: "paparac",
    count: 6,
  },
  {
    id: 13,
    name: "dust",
    attribute: "oth",
    group: "other",
    source: "paparac",
    count: 5,
  },
  {
    id: 14,
    name: "sand",
    attribute: "oth",
    group: "other",
    source: "paparac",
    count: 2,
  },
  {
    id: 15,
    name: "stone",
    attribute: "oth",
    group: "metal",
    source: "paparac",
    count: 5,
  },
];

export default inventory;
